name: car-classification
channels:
  - pytorch-nightly
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - seaborn
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - rich==13.9.4
  - ipywidgets
  - pip 
  pip:
    - "ray[tune]"
    - fastapi
    - uvicorn
    - python-multipart