name: car-classification
channels:
  - defaults
  # - conda-forge
dependencies:
  - python=3.9
  - seaborn
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - rich==13.9.4
  - ipywidgets
  - pip 
  - pip:
    - -r requirements.txt