name: car-classification
channels:
  - defaults
  # - conda-forge
dependencies:
  - python=3.9
  - seaborn=0.13.2
  - numpy=1.26.4
  - pandas=2.2.3
  - matplotlib=3.9.2
  - scikit-learn=1.5.2
  - rich==13.9.4
  - ipywidgets=8.1.5
  - pytest=7.4.4
  - pip 
  - pip:
    - torch==2.6.0
    - torchaudio==2.6.0
    - torchvision==0.21.0
    - ipykernel==6.29.5
    - "ray[tune]==2.41.0"
    - fastapi==0.115.7
    - uvicorn==0.34.0
    - python-multipart==0.0.20
    - requests==2.32.3
    - pyyaml==6.0.2